version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=studentdb
      - POSTGRES_USER=studentuser
      - POSTGRES_PASSWORD=studentpass

  api:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/studentdb
      - SPRING_DATASOURCE_USERNAME=studentuser
      - SPRING_DATASOURCE_PASSWORD=studentpass

volumes:
  db_data: