apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: student-api
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/studentdb"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: student-api
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: OwnerReference
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: studentdb
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: studentdb
        property: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - application
      containers:
        - name: student-api
          image: studentapi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: student-api
  namespace: student-api
spec:
  selector:
    app: student-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer